Add loading states to the purchase flow initialization
0xsequence/marketplace-sdk pull request #86
Opened 2024-12-18 15:09 UTC by RichardIrala

2024-12-18 19:52 UTC, w1that requested changes
Good work @RichardIrala , thanks! I left some comments 👇🏼 

Ideally let's not bring modal specific logic into Transaction machine related classes and methods, instead we can control over loading states in modals. How does look something like below? 
You can find similar approaches we applied to other modals except the Buy Modal. (_e.g. packages/sdk/src/react/ui/modals/MakeOfferModal/index.tsx_)

![Ekran Resmi 2024-12-18 22 49 06](https://github.com/user-attachments/assets/6e225185-d2bd-4c7b-a9d6-849f029355ae)

2024-12-18 19:52 UTC, w1that commented on packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
> +	async start(props: Input, changeCheckoutIsLoading?: (value: boolean) => void) {
It makes start methods `correlated` to checkout modal. However it's a part of the `TransactionMachine` and used by listing, offer, selling, cancelling modals.

2024-12-18 19:52 UTC, w1that commented on packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
> +				buyModal$.close();
I have used something similar, and used external state in the machine which turns out multiple initializations of the machine.

2024-12-19 12:53 UTC, w1that commented on packages/sdk/src/react/ui/modals/BuyModal/_store.ts
> +		buyModal$.isCheckoutLoading.set(true);
Can't we have just `isCheckoutLoading` to handle modal loading? I don't know if other two are needed. Wdyt?

2024-12-19 12:53 UTC, w1that commented on packages/sdk/src/react/ui/modals/_internal/components/actionModal/ActionModal.tsx
> +import type { ComponentProps, ReactNode } from 'react';
Let's remove ReactNode import here ✌🏼

2024-12-19 12:56 UTC, w1that commented on packages/sdk/src/react/ui/modals/BuyModal/index.tsx
> +	if (isCheckoutLoading) {
We have click event listener of cta of `ERC1155QuantityModal`. You can use `buyModal$.isCheckoutLoading.set...`there to have control over loading states. Wdyt?

2025-01-06 20:15 UTC, RichardIrala commented on packages/sdk/src/react/ui/modals/BuyModal/_store.ts
> +		buyModal$.isCheckoutLoading.set(true);
Ok, I modified it

2025-01-06 20:15 UTC, RichardIrala commented on packages/sdk/src/react/ui/modals/_internal/components/actionModal/ActionModal.tsx
> +import type { ComponentProps, ReactNode } from 'react';
Done

2025-01-06 20:20 UTC, RichardIrala commented on packages/sdk/src/react/ui/modals/BuyModal/index.tsx
> +	if (isCheckoutLoading) {
I think I don't quite understand. The issue with the loadings and where I placed its changes in the code is caused by asynchronous code there that needs to be awaited to show or hide loadings. That’s the main reason why I added it to the machine.

2025-01-06 20:21 UTC, RichardIrala commented on packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
> +
The reason I include it here is that the issue with the loading specifically happens here. If I placed it outside, it would never be as synchronized and/or the loading would never be turned off.

2025-01-06 20:24 UTC, RichardIrala commented on packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
> +
Play with **/marketplace-sdk/packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts** by moving the buyModal$.isCheckoutLoading.set(false); and buyModal$.close(); functions below await this.openPaymentModalWithPromise(paymentModalProps);, and you'll see what I mean. If you come up with a better way to handle it, it's more than welcome.

2025-01-06 20:32 UTC, RichardIrala commented on packages/sdk/src/react/ui/modals/BuyModal/index.tsx
> +	if (isCheckoutLoading) {
btw, there, I created isCheckoutLoading because without the useSelector, buyModal$.isCheckoutLoading is not a hook, so the setting of true or false isn't reflected, and the loading doesn't appear in the UI.

2025-01-07 14:06 UTC, w1that commented
Thanks for the descriptive comments @RichardIrala ! I would do the following:
1. pass a parameter to `useBuyCollectable` like `setPaymentLoadingModalOpen`
2. We return a buy function from useBuyCollectible, I would use the passed param here:
```typescript
buy: (props: BuyInput) => {
      if (!machine || isLoading) return;
      setPaymentLoadingModalOpen(true);
      machine.start(props);
    },
``` 
3. Also pass a new optional param to `useTransactionMachine`, `onPaymentModalLoaded`
```typescript
    onPaymentModalLoaded: () => {
      setPaymentLoadingModalOpen(false);
    },
``` 
4. Lastly, we can pass it to `TransactionMachine` and use it in `executeBuyStep`:
```typescript
        this.onPaymentModalLoaded();
        await this.openPaymentModalWithPromise(paymentModalProps);
``` 

Also, we can consider taking your improvements as is until upcoming refactor on Kit side arrives. @AlexanderKolberg wdyt?

2025-01-07 15:59 UTC, AlexanderKolberg commented on packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
> +		if (buyModal$.isOpen.get()) buyModal$.isCheckoutLoading.set(true);
For this to work the transaction machine needs to be wrapped in an observer. The machine should be able to work standalone without external stores or observer functions

2025-01-08 16:44 UTC, RichardIrala commented on packages/sdk/src/react/_internal/transaction-machine/execute-transaction.ts
> +		if (buyModal$.isOpen.get()) buyModal$.isCheckoutLoading.set(true);
I deleted that

2025-01-09 06:05 UTC, AlexanderKolberg approved these changes
LGTM

2025-01-09 06:09 UTC, merged